### ISSUE TITLE
Input Access

### ISSUE THREAD

**Issue by phuree100** [whs/score#2]
Uh, It Must Be Bug On **.htaccess** on /input
That file that input can be **download** by client,
And some school use a master,
They deployed must be fix,

That is not **dangerous**?
Code Verison: Master

**Comment by phuree100** [comment]
But i know it **8 years**

**Comment by whs** [comment]
The /input directory has `Deny from all`:

https://github.com/whs/score/blob/da59b8e084d2a99064ff016303c786961443c040/backend/input/.htaccess#L2

Seems that the list here

https://github.com/whs/score/blob/v2/Gulpfile.js#L51

doesn't copy the .htaccess file so the input directory is left unprotected.

There are still other protection layers in place though:

1. The directory has index.html, so the attacker must know the filename
2. The CSV filename is derived from hmac of the file id. To know the filename, the attacker must know the HMAC key.

The documentation is not doing well for 2) (in fact the install guide is for v1). If one is using the Docker version then the launch script generate a new key. Otherwise, they probably find config.php themselves and see that there's a default key. It is up to the user to figure out that they need to change the key.

**Comment by phuree100** [comment]
Oh Thanks

**Comment by whs** [comment]
Released v2.0.1 to ship the missing .htaccess file. Thank you for the report!

By the way I'd love to hear that any school (apart from mine) is actually using this in production.

**Comment by phuree100** [comment]
I'm from same school that you...
